    const games_db = [
    /*{
        title: "Template",
        image: "img/template.jpg",
        aspect: "32x9", Image aspect ratio. Prefer 1x1
        player_nb: "3 à 4",
        player_filter: "all,one,two,three,four,five,more", list all the possibilities
        category: "",
        category_filter: "",  one is recommended,
        type_filter: "board",        duration_min: "60 à 90",
        duration_filter: "long", short < 30min < mid < 60 min < long
        goal: "Ceci est la description rapide du jeu"
    },*/
    {
        title: "Catane",
        image: "img/games/catane.jpg",
        player_nb: "3 à 4",
        player_filter: "all,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",        type_filter: "board",        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Collecter des ressources et construire des colonies pour être le premier à atteindre 10 points de victoire."
    },
    {
        title: "Andor: Entrez dans la légende",
        image: "img/games/andor1.jpg",
        player_nb: "2-4 joueurs",
        player_filter: "all,two,three,four",
        category: "Aventure</br>Optimisation",
        category_filter: "adventure,optimisation",
        type_filter: "board,cooperation",        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Incarnez les héros Andor et partez à l'aventure pour protéger le royaume des forces du mal. "
    },
        {
        title: "Andor 2 : Le Voyage vers le Nord",
        image: "img/games/andor2.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Aventure</br>Optimisation",
        category_filter: "adventure,optimisation",
        type_filter: "board,cooperation",
        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Aider les héros à se frayer un chemin à travers les montagnes enneigées pour atteindre le Nord et sauver leur terre de l'obscurité qui la menace."
    },
    {
        title: "Andor 3 : La Dernière Espoir",
        image: "img/games/andor3.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Aventure</br>Optimisation",
        category_filter: "adventure,optimisation",
        type_filter: "board,cooperation",
        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Aider les héros à sauver le château de l'assaut des ennemis et à rassembler les dernières forces pour affronter la créature qui menace Andor."
    },
    {
        title: "The Crew: en quête de la neuvième planète",
        image: "img/games/crew_space.png",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation</br>Plis",
        category_filter: "optimisation,fold", 
        type_filter: "cards,cooperation",        duration_min: "20",
        duration_filter: "short",
        goal: "Un jeu de plis où chacun doit accomplir ses missions en remportant des cartes spécifiques dans ses plis."
    },
    {
        title: "The Crew: mission sous-marine",
        image: "img/games/crew_submarine.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation</br>Plis",
        category_filter: "optimisation,fold", 
        type_filter: "cards,cooperation",        duration_min: "20",
        duration_filter: "short",
        goal: "Un jeu de plis où chacun doit accomplir ses missions en remportant des cartes spécifiques dans ses plis."
    },
    {
        title: "Dobble",
        image: "img/games/dobble.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Rapidité</br>Observation",
        category_filter: "speed,observation",
        type_filter: "cards,fast_rules",        duration_min: "15",
        duration_filter: "short",
        goal: "Être le premier à identifier le symbole commun entre deux cartes. Les cartes ont une image en commun, mais il faut être rapide pour la trouver avant les autres joueurs."
    },
    {
        title: "6 qui prend",
        image: "img/games/6quiprend.jpg",
        player_nb: "2 à 10",
        player_filter: "all,two,three,four,five,more",
        category: "Optimisation</br>Hasard",
        category_filter: "optimisation,luck",
        type_filter: "cards",        duration_min: "45",
        duration_filter: "mid",
        goal: "Poser vos cartes en évitant de prendre des têtes de taureaux. Mais attention de ne pas poser la 6ème carte !"
    },
    {
        title: "Welcome to your new home",
        image: "img/games/welcome.jpg",
        player_nb: "1 à 100",
        player_filter: "all,one,two,three,four,five,more",
        category: "Optimisation",
        category_filter: "optimisation",
        type_filter: "cards",        duration_min: "25",
        duration_filter: "short",
        goal: "Construire la ville parfaite pour attirer des habitants, en dessinant des maisons et en marquant des points en fonction des aménagements de la ville."
    },
    {
        title: "Bang",
        image: "img/games/bang.jpg",
        player_nb: "4 à 7",
        player_filter: "all,four,five,more",
        category: "Bluff</br>Bataille",
        category_filter: "bluff,battle",
        type_filter: "cards",        duration_min: "30",
        duration_filter: "mid",
        goal: "Avec le jeu Bang !, devenez Shérif, Hors-la-loi ou Renégat et triomphez de vos adversaires ! Un jeu de cartes à l'ambiance survoltée dans l'univers du Far West !"
    },
    {
        title: "Not Alone",
        image: "img/games/not_alone.jpg",
        player_nb: "2 à 7",
        player_filter: "all,two,three,four,five,more",
        category: "Bluff</br>Bataille",
        category_filter: "bluff,battle",
        type_filter: "board,cards,cooperation",        duration_min: "45",
        duration_filter: "mid",
        goal: "Un joueur incarne une créature extraterrestre chassant les autres joueurs, qui jouent des survivants échoués sur une planète inconnue, et doivent essayer de s'échapper avant d'être alienés."
    },
    {
        title: "La guerre des moutons",
        image: "img/games/guerre_moutons.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management", 
        type_filter: "board",        duration_min: "30 à 60",
        duration_filter: "mid",
        goal: "Construisez votre propre étable et prenez possession de la colline pour gagner la guerre des moutons!"
    },
    {
        title: "Beyond Baker Street",
        image: "img/games/beyond_baker_street.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Optimisation",
        category_filter: "optimisation",         type_filter: "cards,cooperation",        duration_min: "30 à 60",
        duration_filter: "mid",
        goal: "Travaillez ensemble pour accumuler les indices et battre le fameux Sherlock Holmes !"
    },
    {
        title: "Mysterium Park",
        image: "img/games/mysterium_park.jpg",
        player_nb: "2 à 6",
        player_filter: "all,two,three,four,five,six",
        category: "Devinette</br>Observation",
        category_filter: "guessing,observation", 
        type_filter: "cards,cooperation",        duration_min: "30 à 60",
        duration_filter: "mid",
        goal: "En tant que médiums, vous devez communiquer avec le fantôme et résoudre son meurtre pour libérer son âme de l'emprise du parc d'attractions hanté."
    },
    {
        title: "Codenames",
        image: "img/games/codenames.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Devinette",
        category_filter: "guessing", 
        type_filter: "cards,fast_rules",        duration_min: "15 à 30",
        duration_filter: "short",
        goal: "Un jeu d'association d'idées où les joueurs doivent deviner les mots qui correspondent à leur équipe sans tomber dans les pièges des mots des autres équipes."
    },
    {
        title: "Monopoly Deal",
        image: "img/games/monopoly_deal.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Hasard",
        category_filter: "luck", 
        type_filter: "cards",        duration_min: "15 à 30",
        duration_filter: "short",
        goal: "Obtenez des propriétés, des collections et des devises pour être le premier à atteindre 3 ensembles complets dans ce jeu de cartes tirés du célèbre jeu de plateau."
    },
    {
        title: "Dobble Star Wars",
        image: "img/games/dobble_sw.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Rapidité</br>Observation",
        category_filter: "speed,observation", 
        type_filter: "cards,fast_rules",        duration_min: "10",
        duration_filter: "short",
        goal: "Une adaptation du jeu de rapidité Dobble avec des images de l'univers Star Wars."
    },
    {
        title: "Skyjo",
        image: "img/games/skyjo.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Hasard</br>Optimisation",
        category_filter: "luck,optimisation", 
        type_filter: "cards,fast_rules",        duration_min: "15 à 30",
        duration_filter: "short",
        goal: "Collectez le moins de points possible en échangeant vos cartes pour avoir la plus petite somme possible dans ce jeu de cartes amusant et addictif."
    },
    {
        title: "Jaipur",
        image: "img/games/jaipur.jpg",
        player_nb: "2",
        player_filter: "all,two",
        category: "Gestion</br>Développement",
        category_filter: "management", 
        type_filter: "board",        duration_min: "30",
        duration_filter: "mid",
        goal: "En tant que marchands, vous devez acheter les meilleurs ressources ou les trocker contre des chameaux. Un jeu de cartes rapide et stratégique."
    },
    {
        title: "Jungle Speed",
        image: "img/games/jungle_speed.jpg",
        player_nb: "3 à 8",
        player_filter: "all,three,four,five,more",
        category: "Rapidité</br>Observation",
        category_filter: "speed,observation", 
        type_filter: "cards,fast_rules",        duration_min: "15",
        duration_filter: "short",
        goal: "Soyez le plus rapide à attraper le totem lorsque deux signes identiques apparaissent."
    },
    {
        title: "Fuse",
        image: "img/games/fuse.jpg",
        player_nb: "1 à 5",
        player_filter: "all,one,two,three,four,five",
        category: "Rapidité</br>Optimisation",
        category_filter: "speed,optimisation", 
        type_filter: "dice,fast_rules,cooperation",        duration_min: "10",
        duration_filter: "short",
        goal: "Travaillez en équipe pour désamorcer des bombes dans un temps limité à l'aide de combinaison de dés."
    },
    {
        title: "Mr Jack",
        image: "img/games/mr_jack.jpg",
        player_nb: "2",
        player_filter: "all,two",
        category: "Optimisation</br>Bataille",
        category_filter: "optimisation,battle", 
        type_filter: "board",        duration_min: "45",
        duration_filter: "mid",
        goal: "Un jeu de déduction où un joueur incarne le criminel Mr Jack et l'autre joueur incarne l'inspecteur qui doit le démasquer."
    },
    {
        title: "Splendor",
        image: "img/games/splendor.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",         type_filter: "board",        duration_min: "30",
        duration_filter: "short",
        goal: "Un jeu de stratégie où les joueurs doivent acquérir des pierres précieuses pour les échanger contre des cartes de développement qui leur rapporteront des points de prestige."
    },
    {
        title: "Dice Town",
        image: "img/games/dice_town.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Hasard</br>Gestion</br>Développement",
        category_filter: "luck,management",
        type_filter: "board,dice",        duration_min: "45",
        duration_filter: "mid",
        goal: "Un jeu de dés dans le Far West où les joueurs tentent d'accumuler le plus de points de victoire à l'aide de propriétés ou de pépites d'or.'"
    },
    {
        title: "Paléo",
        image: "img/games/paleo.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "cards,cooperation",        duration_min: "45 à 60",
        duration_filter: "mid",
        goal: "Les joueurs doivent collaborer pour survivre dans un monde préhistorique en collectant des ressources, en construisant des abris et en faisant face à des événements aléatoires."
    },
    {
        title: "Agricola",
        image: "img/games/agricola.jpg",
        player_nb: "1 à 4",
        player_filter: "all,one,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board",        duration_min: "120",
        duration_filter: "long",
        goal: "Un jeu de gestion de ferme où les joueurs doivent développer leur exploitation en plantant des cultures, en élevant du bétail et en agrandissant leur maison. Le joueur avec le plus de points de victoire à la fin de la partie gagne."
    },
    {
        title: "Notre Dame",
        image: "img/games/notre_dame.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board",        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Gérer votre quartier de Paris et developpez vos bâtiments pour marquer des points de victoire."
    },
    {
        title: "Thurn & Taxis",
        image: "img/games/thurn_taxis.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board",        duration_min: "60",
        duration_filter: "long",
        goal: "Construisez votre réseau postal en connectant des villes pour gagner des points de victoire."
    },
    {
        title: "Concept",
        image: "img/games/concept.jpg",
        player_nb: "4 à 12",
        player_filter: "all,four,five,more",
        category: "Devinette",
        category_filter: "guessing",
        type_filter: "board",        duration_min: "30",
        duration_filter: "short",
        goal: "Faites deviner des mots ou des expressions en utilisant des icônes universelles pour créer des concepts et sous-concepts."
    },
    {
        title: "7 Wonders",
        image: "img/games/7wonders.jpg",
        player_nb: "3 à 7",
        player_filter: "all,three,four,five,more",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "cards",        duration_min: "30 à 60",
        duration_filter: "mid",
        goal: "Construisez votre merveille et développez votre cité pour marquer le plus de points de victoire à la fin des trois âges."
    },
    {
        title: "Evo",
        image: "img/games/evo.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board",        duration_min: "60",
        duration_filter: "long",
        goal: "Faites évoluer votre espèce de dinosaures pour survivre et dominer l'écosystème.",
    },
    {
        title: "Les Piliers de la Terre",
        image: "img/games/piliers_terre.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management", 
        type_filter: "board",        duration_min: "90",
        duration_filter: "long",
        goal: "Participez à la construction de la cathédrale de Kingsbridge et utilisez vos ressources pour être le joueur le plus influent.",
    },
    {
        title: "Mysterium",
        image: "img/games/mysterium.jpg",
        player_nb: "2 à 7",
        player_filter: "all,two,three,four,five,more",
        category: "Devinette</br>Observation",
        category_filter: "guessing,observation",
        type_filter: "cards,cooperation",        duration_min: "45",
        duration_filter: "mid",
        goal: "Résolvez le meurtre d'un fantôme en tant que médiums, en interprétant ses visions pour trouver le lieu, l'arme et le coupable.",
    },
    {
        title: "Magic Maze",
        image: "img/games/magic_maze.png",
        player_nb: "1 à 8",
        player_filter: "all,one,two,three,four,five,more",
        category: "Rapidité</br>Optimisation",
        category_filter: "speed,optimisation",
        type_filter: "board",        duration_min: "15",
        duration_filter: "short",
        goal: "Aidez des personnages à voler des objets dans un centre commercial. Coordonnez-vous bien car le temps presse !",
    },
    {
        title: "Tabou XXL",
        image: "img/games/taboo_xxl.jpg",
        player_nb: "4 à 20",
        player_filter: "four,five,more",
        category: "Devinette</br>Fun",
        category_filter: "guessing,fun",
        type_filter: "cards",        duration_min: "45",
        duration_filter: "mid",
        goal: "Faites deviner des mots ou des expressions à votre équipe en jouant à 4 minis jeux différents."
    },
    {
        title: "Colt Express",
        image: "img/games/colt_express.jpg",
        player_nb: "2 à 6",
        player_filter: "all,two,three,four,five,six",
        category: "Fun</br>Bataille",
        category_filter: "fun,battle",
        type_filter: "cards",        duration_min: "30 à 40",
        duration_filter: "short",
        goal: "Jeu de programmation où chaque joueur incarne un bandit dans un train en plein Far West. Attention à ce qui peut se passer dans les tunnels !"
    },
    {
        title: "La crique des pirates",
        image: "img/games/crique_pirates.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board,dice",        duration_min: "45",
        duration_filter: "mid",
        goal: "Jeu de stratégie où chaque joueur incarne un pirate et doit constituer la meilleure équipe pour piller des navires."
    },
    {
        title: "Bazar Bizarre",
        image: "img/games/bazar_bizarre.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Rapidité</br>Observation",
        category_filter: "speed,observation",
        type_filter: "cards,fast_rules",        duration_min: "10",
        duration_filter: "short",
        goal: "Jeu de réflexes où il faut être le plus rapide à attraper l'objet correspondant à la carte retournée."
    },
    {
        title: "Onitama",
        image: "img/games/onitama.jpg",
        player_nb: "2",
        player_filter: "all,two",
        category: "Bataille",
        category_filter: "battle",
        type_filter: "board,fast_rules",        duration_min: "15 à 20",
        duration_filter: "short",
        goal: "Jeu de stratégie pour 2 joueurs où chaque joueur contrôle une armée de pions et doit capturer le pion du maître adverse."
    },
    {
        title: "Sleeping Queens",
        image: "img/games/sleeping_queens.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Mémoire</br>Hasard</br>Bataille",
        category_filter: "memory,luck,battle",
        type_filter: "cards, fast_rules",        duration_min: "20",
        duration_filter: "short",
        goal: "Jeu de cartes où le but est de réveiller le plus de reines possible en collectionnant des cartes et en les utilisant pour les réveiller."
    },
    {
        title: "Blokus",
        image: "img/games/blokus.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Optimisation",
        category_filter: "optimisation",
        type_filter: "board,fast_rules",        duration_min: "20 à 30",
        duration_filter: "short",
        goal: "Dans ce jeu de placement de pièces, chaque joueur doit poser le plus de ses pièces sur le plateau en respectant les règles de connexion, sans jamais toucher les coins des pièces de même couleur."
    },
    {
        title: "Dixit",
        image: "img/games/dixit.jpg",
        player_nb: "3 à 6",
        player_filter: "all,three,four,five,more",
        category: "Devinette</br>Observation",
        category_filter: "guessing,observation",
        type_filter: "cards",
        duration_min: "30",
        duration_filter: "short",
        goal: "Dans ce jeu d'association d'idées par image, chaque joueur doit faire deviner une carte de sa main en donnant un indice. Les autres joueurs doivent alors choisir une carte de leur main qui correspond à cet indice. Le but est de marquer le plus de points en faisant deviner sa carte sans être trop évident ni trop obscur."
    },
    {
        title: "Fugi Fugi: La Crypte de la Créature",
        image: "img/games/fugi_fugi.jpg",
        player_nb: "2 à 7",
        player_filter: "all,two,three,four,five,more",
        category: "Fun</br>Optimisation</br>Hasard",
        category_filter: "fun,optimisation,hasard",
        type_filter: "board",
        duration_min: "45",
        duration_filter: "mid",
        goal: "Traversez la crypte avec tous vos personnages. Mais attention à ne pas croiser le chemin de la créature !"
    },
    {
        title: "Les Échecs",
        image: "img/games/chess.jpg",
        player_nb: "2",
        player_filter: "all,two",
        category: "Bataille",
        category_filter: "battle",
        type_filter: "board",
        duration_min: "30 à 60",
        duration_filter: "mid",
        goal: "Dans ce jeu de plateau classique, chaque joueur dispose de seize pièces qu'il doit déplacer sur un plateau de 64 cases. Le but est de mettre en échec et mat le roi adverse en utilisant une combinaison de mouvements de pièces."
    },
    {
        title: "Go",
        image: "img/games/go.jpg",
        player_nb: "2 joueurs",
        player_filter: "two",
        category: "Optimisation</br>Bataille",
        category_filter: "optimisation,battle",
        type_filter: "board",
        duration_min: "30 à 120",
        duration_filter: "mid,long",
        goal: "Capturer plus de territoires que son adversaire en plaçant judicieusement ses pions sur un plateau de jeu de 19x19 intersections."
    },
    {
        title: "Himalaya",
        image: "img/games/himalaya.jpg",
        player_nb: "3 à 4",
        player_filter: "all,three,four",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board,dice",
        duration_min: "60",
        duration_filter: "long",
        goal: "Avec votre caravane de Yack, parcourez les villages de l'Himalaya pour y étendre votre influence sur le plan politique, économique et religieux"
    },
    {
        title: "Shabadabada",
        image: "img/games/shabadabada.jpg",
        player_nb: "3 à 12",
        player_filter: "all,three,four,five,more",
        category: "Fun</br>Mémoire</br>Devinette",
        category_filter: "fun,memory,guessing",
        type_filter: "cards,fast_rules",
        duration_min: "20",
        duration_filter: "short",
        goal: "Chantez le plus d'extrait de chanson qui contiennent un mot imposé."
    },
    {
        title: "The Moose in the House",
        image: "img/games/moose.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Hasard</br>Bataille",
        category_filter: "luck,battle",
        type_filter: "cards,fast_rules",
        duration_min: "10 à 20",
        duration_filter: "short",
        goal: "Les joueurs doivent essayer de placer leurs cartes de moose dans la maison, tout en essayant d'empêcher les autres joueurs de placer les leurs."
    },
    {
        title: "Coloretto",
        image: "img/games/coloretto.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optmisation</br>Hasard",
        category_filter: "luck,optimisation",
        type_filter: "cards",
        duration_min: "30",
        duration_filter: "short",
        goal: "Collecter des cartes de même couleur pour scorer, mais attention à ne pas en avoir trop de couleurs différentes."
    },
    {
        title: "Yams",
        image: "img/games/yams.jpg",
        player_nb: "2 à 10",
        player_filter: "all,two,three,four,five,more",
        category: "Hasard",
        category_filter: "luck",
        type_filter: "dice,fast_rules",
        duration_min: "30",
        duration_filter: "short",
        goal: "Lancer des dés pour obtenir des combinaisons et scorer le plus de points possible."
    },
    {
        title: "L'arche de Noé",
        image: "img/games/arche.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation",
        category_filter: "optimisation",
        type_filter: "cards,fast_rules",
        duration_min: "15",
        duration_filter: "short",
        goal: "Faites partir vos animaux en les répartissant dans les arches."
    },
    {
        title: "Sky my husband",
        image: "img/games/sky_my_husband.jpg",
        player_nb: "2 à 8",
        player_filter: "all,three,four,five,six",
        category: "Fun</br>Devinette",
        category_filter: "fun,guessing",
        type_filter: "cards,fast_rules",
        duration_min: "15",
        duration_filter: "short",
        goal: "Trouvez des expressions anglaises à partir de leur traduction française.."
    },
    {
        title: "Hanabi",
        image: "img/games/hanabi.png",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation</br>Mémoire",
        category_filter: "optimisation,memory",
        type_filter: "cards",
        duration_min: "25",
        duration_filter: "short",
        goal: "Poser vos cartes pour former le plus beau feu d'artifice ! Cependant seul les autres peuvent voir votre jeu."
    },
    {
        title: "Saboteur",
        image: "img/games/saboteur.jpg",
        player_nb: "3 à 10",
        player_filter: "all,three,four,five,more",
        category: "Bluff",
        category_filter: "bluff",
        type_filter: "cards",
        duration_min: "30",
        duration_filter: "short",
        goal: "Creuser un chemin pour trouver de l'or ou saboter le travail des autres pour les empêcher d'atteindre la pépite." 
    },
    {
        title: "Speedy Words",
        image: "img/games/speedy_words.jpg",
        player_nb: "2 à 6",
        player_filter: "all,two,three,four,five,more",
        category: "Devinette",
        category_filter: "guessing",
        type_filter: "cards,fast_rules",
        duration_min: "20",
        duration_filter: "short",
        goal: "Être le plus rapide à trouver un mot en fonction de la première lettre et de la catégorie."
    },
    {
        title: "Time Bomb",
        image: "img/games/time_bomb.jpg",
        player_nb: "4 à 6",
        player_filter: "all,four,five,more",
        category: "Bluff",
        category_filter: "bluff",
        type_filter: "cards",
        duration_min: "15",
        duration_filter: "short",
        goal: "Désamorcez les bombes avant qu'elles n'explosent, en évitant les pièges des saboteurs."
    },
    {
        title: "Sushi Go!",
        image: "img/games/sushi_go.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation",
        category_filter: "optimisation",
        type_filter: "cards",
        duration_min: "20",
        duration_filter: "short",
        goal: "Composez le meilleur menu de sushi en piochant et en passant des cartes à vos adversaires."
    },
    {
        title: "Twinz",
        image: "img/games/twinz.jpg",
        player_nb: "4 à 10",
        player_filter: "all,two,three,four,five,more",
        category: "Devinette",
        category_filter: "guessing",
        type_filter: "cards,fast_rules",
        duration_min: "30",
        duration_filter: "short",
        goal: "Être le plus rapide à trouver un mot par rapport à deux mots proches."
    },
    {
        title: "Panic Lab",
        image: "img/games/panic_lab.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Rapdité</br>Observation",
        category_filter: "speed,observation",
        type_filter: "cards,fast_rules",
        duration_min: "15",
        duration_filter: "short",
        goal: "Trouvez le bon microbes, avant les autres, dans un laboratoire en perpétuel mutation."
    },
    {
        title: "Tropico",
        image: "img/games/tropico.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Mémoire</br>Observation",
        category_filter: "memory,observation",
        type_filter: "cards,fast_rules",
        duration_min: "15",
        duration_filter: "short",
        goal: "Retenez les cartes qui s'emplilent et répondez correctement aux questions posées au fur et à mesure."
    },
    {
        title: "Timeline Science et Exploration",
        image: "img/games/timeline_se.jpg",
        player_nb: "2 à 8",
        player_filter: "all,two,three,four,five,more",
        category: "Devinette",
        category_filter: "guessing",
        type_filter: "cards,fast_rules",
        duration_min: "20",
        duration_filter: "short",
        goal: "Reconstituer une frise en replaçant les cartes dans l'ordre chronologique correct."
    },
    {
        title: "Le Roi des Nains",
        image: "img/games/roi_nains.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Optimisation</br>Hasard</br>Plis",
        category_filter: "optimisation,luck,fold",
        type_filter: "cards",
        duration_min: "45",
        duration_filter: "mid",
        goal: "Une adaptation du jeu de carte \"Le Barbu\""
    },
    {
        title: "Oriflamme",
        image: "img/games/oriflamme.jpg",
        player_nb: "3 à 5",
        player_filter: "all,three,four,five",
        category: "Bluff</br>Bataille",
        category_filter: "bluff,battle",
        type_filter: "cards",
        duration_min: "20",
        duration_filter: "short",
        goal: "Prenez la tête d'une des grandes familles du royaume et user de ruse et de complot pour prendre la succession du roi défunt."
    },
    {
        title: "Niet !",
        image: "img/games/niet.jpg",
        player_nb: "3 à 8",
        player_filter: "all,three,four,five",
        category: "Plis",
        category_filter: "fold",
        type_filter: "cards",
        duration_min: "45",
        duration_filter: "mid",
        goal: "Un jeu de plis classique dans lequel les règles et les équipes changent à chaque manche."
    },
    {
        title: "Canardage",
        image: "img/games/canardage.jpg",
        player_nb: "3 à 6",
        player_filter: "all,three,four,five,more",
        category: "Hasard</br>Fun</br>Bataille",
        category_filter: "luck,fun,battle",
        type_filter: "cards,fast_rules",
        duration_min: "20",
        duration_filter: "short",
        goal: "Les canards barbotent innocement en file indienne. Avec vos cartes, abbatez les autres canards car au final, il ne peut en rester coin !"
    },
    {
        title: "Déclic",
        image: "img/games/declic.jpg",
        player_nb: "3 à 8",
        player_filter: "all,three,four,five,more",
        category: "Fun</br>Rapidité",
        category_filter: "fun,speed",
        type_filter: "cards,fast_rules",
        duration_min: "20",
        duration_filter: "short",
        goal: "Tapez au centre avec votre main vrai ou faux pour répondre aux questions le plus vite possible. Gare aux erreurs !"
    },
    {
        title: "Tchin-tchin",
        image: "img/games/tchin.jpg",
        player_nb: "4 à 8",
        player_filter: "all,four,five,more",
        category: "Fun</br>Rapidité",
        category_filter: "fun,speed",
        type_filter: "cards",
        duration_min: "20",
        duration_filter: "short",
        goal: "Un apéro international où il faudra être le premier à effectuer le bon geste et dire la bonne parole pour trinquer."
    },
    {
        title: "Carcassonne : Mers du Sud",
        image: "img/games/carcassonne_sud.jpg",
        player_nb: "2 à 5",
        player_filter: "all,two,three,four,five",
        category: "Gestion</br>Développement",
        category_filter: "management",
        type_filter: "board",
        duration_min: "30 à 45",
        duration_filter: "mid",
        goal: "Marquer le plus de points en plaçant astucieusement ses tuiles et en créant des réseaux de bateaux et d'îles."
    },
    {
        title: "Les aventures de Robin des Bois",
        image: "img/games/robin_hood.jpg",
        player_nb: "2 à 4",
        player_filter: "all,two,three,four",
        category: "Aventure</br>Optimisation",
        category_filter: "adventure,optimisation",
        type_filter: "board,cooperation",
        duration_min: "60 à 90",
        duration_filter: "long",
        goal: "Embarquez avec vos héros préférés pour une nouvelle aventure ! Il faudra prendre les bonnes décisions pour voir les héros triompher !"
    }
];

const shuffle_array = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        const temp = array[i];

        // Swap
        array[i] = array[j];
        array[j] = temp;
    }
    return array;
};